export const COLORS = [
  "blue",
  "green",
  "orange",
  "purple",
  "cyan",
  "pink",
  "red",
  "yellow",
];

export const CATEGORIES = [
  "productivity",
  "media",
  "infrastructure",
  "security",
  "monitoring",
  "development",
  "networking",
  "storage",
  "automation",
];

/**
 * Emoji dataset organized by category, each with search keywords.
 * Format: [emoji, "search terms"]
 */
export const EMOJI_DATA = {
  "Tech & Devices": [
    ["💻", "laptop computer"],
    ["🖥️", "desktop computer monitor"],
    ["🖱️", "mouse"],
    ["⌨️", "keyboard"],
    ["📱", "phone mobile smartphone"],
    ["📟", "pager"],
    ["🖨️", "printer"],
    ["💾", "floppy disk save"],
    ["💿", "cd disc"],
    ["📀", "dvd disc"],
    ["🔌", "plug power electric"],
    ["🔋", "battery power"],
    ["📡", "satellite antenna signal"],
    ["🖲️", "trackball"],
    ["📠", "fax machine"],
    ["📺", "television tv monitor"],
    ["📻", "radio"],
    ["🎙️", "microphone studio"],
    ["🎚️", "level slider"],
    ["🎛️", "control knobs"],
    ["🕹️", "joystick gaming"],
    ["🤖", "robot bot ai"],
    ["🧮", "abacus calculator"],
  ],
  "Tools & Development": [
    ["🔧", "wrench tool config"],
    ["🔨", "hammer build"],
    ["⚙️", "gear settings config"],
    ["🛠️", "tools hammer wrench"],
    ["⛏️", "pick axe mining"],
    ["🪛", "screwdriver tool"],
    ["🔩", "nut bolt hardware"],
    ["⚡", "lightning bolt power fast"],
    ["🧰", "toolbox"],
    ["🪝", "hook"],
    ["🧪", "test tube experiment"],
    ["🧬", "dna genetics"],
    ["🔬", "microscope science"],
    ["🔭", "telescope explore"],
    ["📐", "triangular ruler"],
    ["📏", "straight ruler"],
    ["🏗️", "building construction crane"],
    ["🐳", "whale docker container"],
    ["🐙", "octopus github git"],
    ["🦊", "fox gitlab"],
    ["🐰", "rabbit bunny gitea"],
    ["🐧", "penguin linux"],
    ["🐍", "snake python"],
    ["🦀", "crab rust"],
    ["☕", "coffee java"],
    ["💎", "gem ruby"],
    ["🐘", "elephant postgres php"],
  ],
  "Security & Locks": [
    ["🔒", "lock locked secure"],
    ["🔓", "unlock unlocked open"],
    ["🔐", "locked key password"],
    ["🔑", "key password auth"],
    ["🗝️", "old key secret"],
    ["🛡️", "shield security protect defense"],
    ["🔏", "lock pen signed"],
    ["🛂", "passport control border"],
    ["🚫", "prohibited blocked forbidden"],
    ["⛔", "no entry stop"],
    ["🚨", "police light alert alarm"],
    ["🔔", "bell notification alert"],
    ["🔕", "bell mute silent"],
    ["👤", "user person account"],
    ["👥", "users people group"],
    ["🕵️", "detective spy investigate"],
    ["👁️", "eye watch monitor"],
    ["🔍", "magnifying glass search left"],
    ["🔎", "magnifying glass search right"],
    ["🛡️", "shield guard protect"],
  ],
  "Cloud & Network": [
    ["☁️", "cloud server hosting"],
    ["🌐", "globe internet web world"],
    ["🌍", "earth globe europe africa"],
    ["🌎", "earth globe americas"],
    ["🌏", "earth globe asia australia"],
    ["📶", "signal bars wireless wifi"],
    ["📡", "satellite dish antenna"],
    ["🔗", "link chain url"],
    ["🔀", "shuffle random proxy"],
    ["🔁", "repeat loop sync"],
    ["🔂", "repeat single once"],
    ["🔃", "clockwise arrows refresh"],
    ["🔄", "counterclockwise arrows sync refresh"],
    ["⬆️", "up arrow upload"],
    ["⬇️", "down arrow download"],
    ["↗️", "arrow upper right"],
    ["↘️", "arrow lower right"],
    ["↔️", "left right arrow bidirectional"],
    ["↕️", "up down arrow vertical"],
    ["🔺", "red triangle up"],
    ["🔻", "red triangle down"],
  ],
  "Files & Data": [
    ["📁", "folder directory"],
    ["📂", "folder open directory"],
    ["📄", "document file page"],
    ["📃", "document page curl"],
    ["📝", "memo note write edit"],
    ["📋", "clipboard paste"],
    ["📎", "paperclip attach"],
    ["🗂️", "card index dividers tabs"],
    ["🗃️", "card file box storage"],
    ["🗄️", "file cabinet storage archive"],
    ["📦", "package box container"],
    ["📊", "bar chart analytics stats"],
    ["📈", "chart trending up growth"],
    ["📉", "chart trending down decline"],
    ["📑", "bookmark tabs"],
    ["🔖", "bookmark tag label"],
    ["🏷️", "label tag price"],
    ["📌", "pushpin pin location"],
    ["📍", "round pushpin location"],
    ["📜", "scroll log old document"],
    ["📰", "newspaper news rss feed"],
    ["🗞️", "rolled newspaper"],
    ["📓", "notebook"],
    ["📔", "notebook decorative"],
    ["📕", "closed book red"],
    ["📖", "open book read"],
    ["📗", "green book"],
    ["📘", "blue book docs"],
    ["📙", "orange book"],
    ["📚", "books library stack"],
  ],
  "Media & Entertainment": [
    ["🎬", "clapper movie film video"],
    ["🎦", "cinema movie theater"],
    ["📷", "camera photo picture"],
    ["📸", "camera flash photo"],
    ["📹", "video camera recording"],
    ["📽️", "film projector movie"],
    ["🎥", "movie camera film"],
    ["🎵", "music note song"],
    ["🎶", "music notes melody"],
    ["🎧", "headphones audio music"],
    ["🎤", "microphone singing karaoke"],
    ["🎮", "game controller gaming"],
    ["🎲", "dice game random"],
    ["🎯", "target bullseye goal"],
    ["🎨", "palette art paint design"],
    ["🎭", "performing arts theater masks"],
    ["🖼️", "frame picture image gallery"],
    ["📺", "tv television shows"],
    ["📻", "radio broadcast"],
    ["🎵", "music streaming audio"],
  ],
  "Status & Indicators": [
    ["✅", "check mark done success"],
    ["❌", "cross mark error fail"],
    ["⚠️", "warning alert caution"],
    ["❗", "exclamation important urgent"],
    ["❓", "question help unknown"],
    ["💡", "light bulb idea tip"],
    ["🔥", "fire hot trending popular"],
    ["⭐", "star favorite rating"],
    ["🌟", "glowing star featured"],
    ["💯", "hundred percent perfect"],
    ["🟢", "green circle online active"],
    ["🔴", "red circle offline error"],
    ["🟡", "yellow circle warning pending"],
    ["🔵", "blue circle info"],
    ["🟣", "purple circle"],
    ["⚪", "white circle"],
    ["⚫", "black circle"],
    ["🚀", "rocket launch deploy fast"],
    ["✨", "sparkles new magic"],
    ["💥", "collision crash boom"],
    ["🎉", "party popper celebrate"],
    ["🏆", "trophy winner achievement"],
    ["🏅", "medal award"],
    ["📣", "megaphone announce broadcast"],
    ["💬", "speech bubble chat message"],
    ["💭", "thought bubble thinking"],
  ],
  "Home & Buildings": [
    ["🏠", "house home"],
    ["🏡", "house garden"],
    ["🏢", "office building"],
    ["🏣", "post office"],
    ["🏥", "hospital medical"],
    ["🏦", "bank financial"],
    ["🏛️", "classical building government"],
    ["🏗️", "building construction"],
    ["🏭", "factory industrial"],
    ["🏪", "convenience store shop"],
    ["🏰", "castle fortress"],
    ["🗼", "tower"],
    ["🏔️", "mountain snow"],
    ["⛰️", "mountain"],
    ["🌋", "volcano"],
    ["🏕️", "camping tent"],
    ["🌅", "sunrise"],
    ["🌄", "sunrise mountains"],
  ],
  Transport: [
    ["🚗", "car automobile"],
    ["🚕", "taxi cab"],
    ["🚀", "rocket ship space launch"],
    ["✈️", "airplane flight"],
    ["🚁", "helicopter"],
    ["🚂", "locomotive train"],
    ["🚢", "ship boat"],
    ["⛵", "sailboat"],
    ["⚓", "anchor ship helm harbor"],
    ["🛰️", "satellite space orbit"],
    ["🛸", "flying saucer ufo"],
  ],
  "Food & Drink": [
    ["☕", "coffee hot drink java"],
    ["🍵", "tea hot drink"],
    ["🍴", "fork knife restaurant food"],
    ["🍽️", "plate cutlery dining"],
    ["🍕", "pizza food"],
    ["🍔", "hamburger food burger"],
    ["🍺", "beer mug drink"],
    ["🥤", "cup straw drink"],
    ["🧁", "cupcake dessert"],
    ["🍰", "cake pie dessert"],
    ["🍎", "apple fruit red"],
    ["🫐", "blueberry fruit"],
  ],
  Symbols: [
    ["♻️", "recycle green sustainability"],
    ["⚛️", "atom science physics"],
    ["☸️", "wheel dharma kubernetes k8s"],
    ["🔰", "beginner japanese symbol"],
    ["♾️", "infinity loop forever"],
    ["‼️", "double exclamation"],
    ["⁉️", "exclamation question"],
    ["〰️", "wavy dash"],
    ["©️", "copyright"],
    ["®️", "registered"],
    ["™️", "trademark"],
    ["#️⃣", "hash number pound"],
    ["*️⃣", "asterisk star keycap"],
    ["🔣", "input symbols"],
    ["🔤", "input latin letters abc"],
    ["🔢", "input numbers 123"],
    ["🆗", "ok button"],
    ["🆕", "new button"],
    ["🆙", "up button"],
    ["🔠", "input latin uppercase"],
    ["ℹ️", "information source"],
    ["🅿️", "parking"],
    ["Ⓜ️", "circled m metro"],
  ],
};

/** Flat list of all emojis (for backward compat) */
export const ALL_EMOJIS = Object.values(EMOJI_DATA)
  .flat()
  .map(([e]) => e);
